name: Windows 2022 RDP with Tailscale

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
    - name: Download Files
      run: |
        Invoke-WebRequest https://storage.curvee.eu.org/tailscale-setup.exe -OutFile tailscale-setup.exe
        Invoke-WebRequest https://storage.curvee.eu.org/start-2022.bat -OutFile start.bat
        Invoke-WebRequest https://storage.curvee.eu.org/wallpaper.png -OutFile wallpaper.png
        Invoke-WebRequest https://storage.curvee.eu.org/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://storage.curvee.eu.org/loop.bat -OutFile loop.bat

    - name: Install Tailscale
      run: Start-Process .\tailscale-setup.exe -Wait

    - name: Start Tailscale
      run: |
        tailscale up --authkey $Env:TAILSCALE_AUTHKEY --hostname github-rdp
      env:
        TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        copy wallpaper.png C:\Users\Public\Desktop\wallpaper.png
        copy wallpaper.bat C:\Users\Public\Desktop\wallpaper.bat

    - name: Connect RDP
      run: cmd /c start.bat

    - name: Keep Alive
      run: cmd /c loop.bat
