name: Windows 2022 RDP with Tailscale

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
    - name: Download Files
      run: |
        # Download Tailscale Setup
        Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale-setup.exe
        # Download RDP-related files (start, wallpaper, loop, etc.)
        Invoke-WebRequest https://raw.githubusercontent.com/p-store13/Rdpone/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/p-store13/Rdpone/main/wallpaper.png -OutFile wallpaper.png
        Invoke-WebRequest https://raw.githubusercontent.com/p-store13/Rdpone/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/p-store13/Rdpone/main/loop.bat -OutFile loop.bat

    - name: Install Tailscale
      run: |
        # Install Tailscale silently
        Start-Process .\tailscale-setup.exe -ArgumentList "/S" -Wait

    - name: Start Tailscale
      run: |
        # Start Tailscale with provided authentication key and hostname
        tailscale up --authkey $Env:TAILSCALE_AUTHKEY --hostname github-rdp
      env:
        TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Enable RDP Access
      run: |
        # Enable RDP access and allow remote desktop connections
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        # Copy wallpaper and batch files to the desktop
        copy wallpaper.png C:\Users\Public\Desktop\wallpaper.png
        copy wallpaper.bat C:\Users\Public\Desktop\wallpaper.bat

    - name: Connect RDP
      run: cmd /c start.bat

    - name: Keep Alive
      run: |
        # Keep the RDP session alive
        cmd /c loop.bat
